version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    container_name: gestor_backend
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/libros

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    container_name: gestor_frontend
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: gestor_mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
